---
- name: toptour
  hosts: "{{ hosts_input | default('default') }}"
  become: yes
  vars:
    app_name: toptour_api
    local_dir: '{{ playbook_dir.split("/")[0:-1]|join("/") }}'
    app_user: "{{ deploy_user | default('vagrant') }}"
    deploy_dir: "/opt/{{app_name}}"
    nodejs_version: "7.x"
    nodejs_install_npm_user: "{{app_user}}"
    database: geodata

  pre_tasks:
    - apt: name=python-psycopg2

  roles:
    # - role: geerlingguy.nodejs
    # - role: kjartab.postgis
    # - role: geerlingguy.redis
    - role: database
      become_user: postgres
    - role: app