---
- name: toptour
  hosts: "{{ hosts_input | default('default') }}"
  become: yes
  vars:
    app_name: toptour_api
    local_dir: '{{ playbook_dir.split("/")[0:-1]|join("/") }}'
    app_user: "{{ deploy_user | default('vagrant') }}"
    deploy_dir: "/opt/{{app_name}}"
    nodejs_version: "7.x"
    nodejs_install_npm_user: "{{app_user}}"
    database: geodata

  pre_tasks:
    - apt: name=python-psycopg2
    - template: src=locale.j2 dest=/etc/default/locale
    # - apt_repository: repo=deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
  
  roles:
    - role: geerlingguy.nodejs
    # - role: ansible-role-postgresql
    # - role: ansible-role-postgis
    # - role: kjartab.tomcat
    # - role: ansible-role-tomcat
    #   tags: tomcat
    # - role: ansible-role-geoserver
    #   tags: geoserver
    - role: database
      tags: db
      become_user: postgres
    # - role: app
