---
- name: toptour
  hosts: "{{ hosts_input | default('default') }}"
  become: yes

  tasks:
    - shell: ansible-galaxy install {{item}}
      with_items:
        - geerlingguy.nodejs
        # - kjartab.postgresql
        # - kjartab.postgis
        # - kjartab.tomcat
        # - kjartab.geoserver
        # - alexeymedvedchikov.rabbitmq
        
    - apt: name=python-psycopg2
